services:
  # AIDocument 服务
  aidocument:
    image: aidocument:v1.2
    container_name: aidocument
    restart: unless-stopped
    volumes:
      - /root/aidocument/Configs:/app/Configs
      - /root/aidocument/Results:/app/Results
      - /root/aidocument/Logs:/app/Logs
    ports:
      - 7001:7001